### ISSUE TITLE
kickstart145() never called, even if version check passed

### ISSUE THREAD

**Issue by gbowsky** [RPwnage/pwn-my#10]
https://github.com/RPwnage/pwn-my/blob/31ca6952889ed16530d228a00e6195511aef64e6/source/js/index.js#L7-L11

Bug/feature or just a small mistake? `kickstart145()` is never called.

**Comment by notbluu** [comment]
Going to post this here and elsewhere on other issues on this repository:

If you did NOT read the README, it should say it's a WIP jailbreak with work needed to be done on it. 

![Screenshot_20210607-231958_Chrome.jpg](https://user-images.githubusercontent.com/56172613/121133261-fca4db00-c7e6-11eb-81c5-3c63ee1cd44a.jpg)

**Comment by RPwnage** [comment]
Thanks for letting me know, I forgot to call it.
