### ISSUE TITLE
[Question] Will this work on 14.6 ?, will it have sileo or cydia?

### ISSUE THREAD

**Issue by Darthveder69420** [RPwnage/pwn-my#12]

**Comment by daniel-inderos** [comment]
It supports IOS 14.5 - 14.6 and I think you will be able to choose if you want Cydia or Sileo but if not it will use Cydia

**Comment by Darthveder69420** [comment]
Ok cool. I needed to update to 14.6.

**Comment by notbluu** [comment]
Going to post this here and elsewhere on other issues on this repository:

If you did NOT read the README, it should say it's a WIP jailbreak with work needed to be done on it. 

![Screenshot_20210607-231958_Chrome.jpg](https://user-images.githubusercontent.com/56172613/121133261-fca4db00-c7e6-11eb-81c5-3c63ee1cd44a.jpg)

**Comment by RPwnage** [comment]
This is not a question that belongs on github. Read the readme or ask non-technical questions on twitter.
