### ISSUE TITLE
Dead project.

### ISSUE THREAD

**Issue by zdc54** [RPwnage/pwn-my#31]
RPwnage is in jail (ironic, right?) for possession of illegal substances (specifically "green leaves) for 4 years. This is an obvious sign that the project is dead. I cannot confirm that Manticore is no longer actively maintained. Manticore will be long gone in 4 years, since we would be on iOS 19 or 20 by then.

**Comment by verygenericname** [comment]
> > RPwnage is in jail (ironic, right?) for possession of illegal substances (specifically "green leaves) for 4 years. This is an obvious sign that the project is dead. I cannot confirm that Manticore is no longer actively maintained. Manticore will be long gone in 4 years, since we would be on iOS 19 or 20 by then.
> 
> Wait is he actually in jail ?

yes. yes he is. This project went nowhere anyways

**Comment by turnerrocks1** [comment]
checkout my repository I will have an updated iOS 14 version soon, for now the only one i have is iOS 12 arb r/w with a dyld shared cache parser the only thing left for me to do is craft a ROP chain.

**Comment by zdc54** [comment]
I'm wondering how he is going to jailbreak his way out of prison this time.

**Comment by RPwnage** [comment]
> I'm wondering how he is going to jailbreak his way out of prison this time.

Don't ask how i did it

**Comment by RouterCFW** [comment]
> > I'm wondering how he is going to jailbreak his way out of prison this time.
> 
> Don't ask how i did it

Lmfao

**Comment by RPwnage** [comment]
revived it
